FROM node:latest
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/deluan/zsh-in-docker/master/zsh-in-docker.sh)" -- \
    -t robbyrussell \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p history-substring-search
WORKDIR /usr/src/app

COPY ./package.json .

EXPOSE 4000
ENTRYPOINT npm install && npm start
